name: Build test.dll

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Install MinGW (32-bit)
        run: choco install mingw --version=12.2.0 --force -y
        shell: powershell

      - name: Setup Java 8 (JDK) - 32-bit
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          architecture: 'x86'

      - name: Compile DLL
        shell: cmd
        run: |
          g++ -shared -o fly.dll fly.cpp -static -luser32 -m32 -I"%JAVA_HOME%\include" -I"%JAVA_HOME%\include\win32"

      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: fly-dll
          path: fly.dll
